### ISSUE TITLE
Bug in upstream dk

### ISSUE THREAD

**Issue by Bleyddyn** [Bleyddyn/malpi#9]
Tub v2's don't handle user meta data correctly.

Meta: {'DONKEY_GYM_ENV_NAME': 'donkey-warehouse-v0', 'JOYSTICK_MAX_THROTTLE': 8.0, 'JOYSTICK_STEERING_SCALE': 1.0, 'location': 'sim', 'task': 'Train', 'driver': 'Andrew'}
Traceback (most recent call last):
  File "scripts/collect_meta.py", line 110, in <module>
    vehicle = MyDriver(cfg, model_path=args['--model'], model_type=model_type, use_joystick=cfg.USE_JOYSTICK_AS_DEFAULT, meta=meta)
  File "scripts/collect_meta.py", line 52, in __init__
    super().__init__(cfg, model_path=model_path, use_joystick=use_joystick, model_type=model_type, camera_type=camera_type, meta=meta )
  File "/home/andrew/malpi/malpi/dk/drive.py", line 111, in __init__
    self.build(camera_type=camera_type)
  File "/home/andrew/malpi/malpi/dk/drive.py", line 130, in build
    self.build_recording()
  File "/home/andrew/malpi/malpi/dk/drive.py", line 651, in build_recording
    tub_writer = TubWriter(tub_path, inputs=inputs, types=types, metadata=self.meta)
  File "/home/andrew/donkeycar/donkeycar/parts/tub_v2.py", line 114, in __init__
    self.tub = Tub(base_path, inputs, types, metadata, max_catalog_len)
  File "/home/andrew/donkeycar/donkeycar/parts/tub_v2.py", line 26, in __init__
    self.manifest = Manifest(base_path, inputs=inputs, types=types,
  File "/home/andrew/donkeycar/donkeycar/parts/datastore_v2.py", line 234, in __init__
    self._read_metadata(metadata)
  File "/home/andrew/donkeycar/donkeycar/parts/datastore_v2.py", line 320, in _read_metadata
    for (key, value) in metadata:
ValueError: too many values to unpack (expected 2)

**Comment by Bleyddyn** [comment]
Fixed this by passing data differently. Commit 7993ff0c5197d9325cb92ab6fc346db70e1355a3
